[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = 
    -D NODE_IS_MASTER=0

[env:seeed_xiao_esp32s3_ota]
extends = env:seeed_xiao_esp32s3
upload_protocol = custom
; Replace with the actual IP address of your ESP32
upload_flags =
    http://192.168.3.14/update
upload_command = curl -X POST --data-binary @$SOURCE $UPLOAD_FLAGS

[env:seeed_xiao_esp32s3_ota_fleet]
extends = env:seeed_xiao_esp32s3
upload_protocol = custom
upload_command = python tools/ota_flash_all.py $SOURCE

[env:lolin_s2_mini]
platform = espressif32
board = lolin_s2_mini
framework = espidf
monitor_speed = 115200
build_flags = 
    -D BOARD_LOLIN_S2_MINI
    -D NODE_IS_MASTER=1
board_build.cmake_extra_args = 
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.s2_mini"

[env:esp32_s3_devkitc_1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv
board_build.cmake_extra_args = 
    -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;sdkconfig.defaults.esp32_s3_devkitc_1"
build_flags = 
    -D BOARD_ESP32_S3_DEVKITC_1
    -D NODE_IS_MASTER=0
    -D BOARD_HAS_PSRAM

[env:esp32_s3_devkitc_1_ota]
extends = env:esp32_s3_devkitc_1
upload_protocol = custom
; Replace with the actual IP address of your Devkit
upload_flags =
    http://192.168.3.10/update
upload_command = curl -X POST --data-binary @$SOURCE $UPLOAD_FLAGS